name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 64000
        script: |
            if [ ! -d "/var/www/html/cicd" ]; then
              mkdir -p /var/www/html/cicd
            fi

            if [ ! -d "/var/www/html/cicd/nim_kalian" ]; then
              mkdir -p /var/www/html/cicd/nim_kalian
            fi

            cd /var/www/html/cicd/nim_kalian

            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }}.git .
            else
              git pull origin main
            fi

            chmod -R 755 /var/www/html/cicd